spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hayaking/spring-cloud-config.git
          search-paths:
server:
  port: 8888
