spring:
  application:
    name:  config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/icoreman/spring-cloud-config-demo1.git #GitHub上面的git仓库名字
server:
  port: 8888
