server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
spring:
  application:
    name: service-consumer

feign:
  hystrix:
    enabled: true
