spring:
  application:
    name: zuul
  profiles:
    active: dev
server:
  port: 8083
eureka:
  instance:
    hostname: 39.105.163.41
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka
zuul:
  routes:
    api-a:
      path: /A/**
      serviceId: service-consumer
